services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpwd
      POSTGRES_DB: web_II
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./dump:/data


volumes:
  pgdata: